# Generated by Django 5.1 on 2024-11-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcall',
            options={'ordering': ['-time_created'], 'verbose_name': 'Обратный звонок', 'verbose_name_plural': 'Обратные звонки'},
        ),
        migrations.AddField(
            model_name='feedbackcall',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Отметка о выполнении'),
        ),
        migrations.AlterField(
            model_name='feedbackcall',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
